
using DataMock;
using Net;
using Newtonsoft.Json;
using System;
using System.IO;

namespace ClientRaspil
{
    class Program
    {
       
        static void Main(string[] args)
        {
            prog1(args);
           
        }

        private static void prog1(string[] args)
        {
            AppExchangeClient clinet;
            if (args.Length > 0)
                clinet = new AppExchangeClient("127.0.0.1", args[0]);
            else 
                clinet = new AppExchangeClient("127.0.0.1", "49770");

            var (orders, store) = Data.autoGeneratedData(30, 60, 5, args.Length > 2 ? false : true, true);

            var xx = new ClientData
            {
                orders = orders,
                store = store,
                widthSaw = 4,
                algoritm = 1
            };

            var newData = JsonConvert.SerializeObject(xx);

            clinet.Send(newData);

            
            var d = clinet.Receive();

            File.AppendAllText(Path.Combine(Directory.GetCurrentDirectory(), "out.txt"), d + "\n");
            d = clinet.Receive();
            File.AppendAllText(Path.Combine(Directory.GetCurrentDirectory(), "out.txt"), d + "\n");
            Console.WriteLine(d);
            Console.ReadLine();


        }
    }

    
}
