
using DataMock;
using Net;
using Newtonsoft.Json;
using System;
using System.IO;

namespace ClientRaspil
{
    class Program
    {
       
        static void Main(string[] args)
        {
            prog1();
           
        }

        private static void prog1()
        {
            AppExchangeClient clinet = new AppExchangeClient("127.0.0.1", "49770");

            var (orders, store) = Data.autoGeneratedData(30, 60, 5, false, true);

            var xx = new ClientData
            {
                orders = orders,
                store = store,
                widthSaw = 4,
                algoritm = 1
            };
            var newData = JsonConvert.SerializeObject(xx);

            clinet.Send(newData);

            var d = clinet.Receive();

            File.WriteAllText(Path.Combine(Directory.GetCurrentDirectory(), "out"), d);
            Console.WriteLine(d);
            Console.ReadLine();


        }
    }

    
}
